### ISSUE TITLE
Update outline

### ISSUE THREAD

**Issue by fonnesbeck** [fonnesbeck/ngcm_pandas_2017#1]
The dates have been updated to the 2017 dates already. 

Since there will be a `sklearn` module this year, we can get rid of that portion. Anything we want to add or change? A few ideas:

- [ ] the latest `pandas` innovations since last year (*i.e.* 0.19 stuff)
  - [ ] BigQuery/s3 facilities (?)
  - [ ] Chunked read_csv (index improvements)
  - [ ] .agg and .transform API
  - [ ] GroupBy can now use column and index-levels
  - [ ] scipy.sparse matrix support
  - [ ] anything else?
- [ ] a capstone project for the last hour, perhaps using an actual "big dataset" (*e.g.* NYC taxis)
- [ ] expanded `seaborn`/`bokeh`, including plotting "best practices"

**Comment by fonnesbeck** [comment]
Not sure how much we need to change from last year. We may want to drop the dask and sklearn sections, but not all students will be taking both, and the dask will be more general here than when associated with sklearn. I could go either way.

**Comment by jseabold** [comment]
I would vote for dropping scikit-learn, since we'll be doing a ton of it. If they want it, they can take the class. We usually run out of time during plotting, so we could stretch a bit more maybe. As for dask, I don't have a strong opinion. If we leave it, I'd like to introduce some more general comments about MapReduce and cloud computing -- can tie back in to where pandas touches the cloud, perhaps.

**Comment by fonnesbeck** [comment]
Sounds good. I think dask still makes sense here, or some type of out-of-core data processing. Dask is great because you can teach most of the good stuff locally, without having to fire up a cluster.

**Comment by fonnesbeck** [comment]
I've removed the scikit-learn section, and dropped in an analysis module that only uses pandas, numpy and scipy. Still needs some work, though.

**Comment by fonnesbeck** [comment]
I've done most of this. Closing.
